/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanaherramientas;

import javax.swing.JFrame;
import org.bolivia.app.interfaz;

/**
 *
 * @author Anthony
 */
public class WinGestionarProyecto extends javax.swing.JFrame {

    /**
     * Creates new form WinLogin
     */
 JFrame j1;
    public WinGestionarProyecto(JFrame j1) {
        this.j1=j1;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_crear_proyecto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_modificar_proyecto = new javax.swing.JButton();
        bt_consultar_proyecto = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_crear_proyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_crear_proyecto.setText("Crear Proyecto");
        bt_crear_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crear_proyectoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel3.setText("Gestionar Proyecto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setText("Todos los derechos reservados JAD Solutions S.A. © ");

        bt_modificar_proyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_modificar_proyecto.setText("Modificar Proyecto");
        bt_modificar_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificar_proyectoActionPerformed(evt);
            }
        });

        bt_consultar_proyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_consultar_proyecto.setText("Consultar Proyecto");
        bt_consultar_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consultar_proyectoActionPerformed(evt);
            }
        });

        btnvolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnvolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_crear_proyecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_modificar_proyecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(bt_consultar_proyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(bt_crear_proyecto)
                .addGap(46, 46, 46)
                .addComponent(bt_modificar_proyecto)
                .addGap(54, 54, 54)
                .addComponent(bt_consultar_proyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnvolver)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crear_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crear_proyectoActionPerformed
        this.setVisible(false);
        new interfaz(this).setVisible(true);
    }//GEN-LAST:event_bt_crear_proyectoActionPerformed

    private void bt_modificar_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificar_proyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_modificar_proyectoActionPerformed

    private void bt_consultar_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consultar_proyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_consultar_proyectoActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
       j1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_consultar_proyecto;
    private javax.swing.JButton bt_crear_proyecto;
    private javax.swing.JButton bt_modificar_proyecto;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
