/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanaherramientas;

/**
 *
 * @author Anthony
 */
public class WinPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form WinLogin
     */
    public WinPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_gestionar_proyecto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bt_gestionar_herramienta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_gestionar_proyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_gestionar_proyecto.setText("Gestionar Proyecto");
        bt_gestionar_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gestionar_proyectoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel3.setText("ENCOFRAP");

        bt_gestionar_herramienta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_gestionar_herramienta.setText("Gestionar Herramientas");
        bt_gestionar_herramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gestionar_herramientaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setText("Todos los derechos reservados JAD Solutions S.A. © ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_gestionar_herramienta, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(bt_gestionar_proyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(74, 74, 74)
                .addComponent(bt_gestionar_proyecto)
                .addGap(57, 57, 57)
                .addComponent(bt_gestionar_herramienta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_gestionar_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gestionar_proyectoActionPerformed
        // TODO add your handling code here:
        WinGestionarProyecto wingestpro1 = new WinGestionarProyecto(this);
        setVisible(false);
        wingestpro1.setVisible(true);
    }//GEN-LAST:event_bt_gestionar_proyectoActionPerformed

    private void bt_gestionar_herramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gestionar_herramientaActionPerformed
       setVisible(false);
       new FrmHerramientas2().setVisible(true);
    }//GEN-LAST:event_bt_gestionar_herramientaActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_gestionar_herramienta;
    private javax.swing.JButton bt_gestionar_proyecto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
